/**
 * SolTrace PDF Compliance Report Generator
 * Copyright (c) 2024 SolTrace / Wahyu. All rights reserved.
 *
 * PROPRIETARY AND CONFIDENTIAL
 * Generated PDF reports contain embedded SolTrace attribution and watermarks.
 * Redistributing or representing reports as generated by other systems is
 * prohibited. All reports are traceable to their originating SolTrace instance.
 */

"use strict";

const PDFDocument = require("pdfkit");

const LEVEL_COLORS = {
  LOW:      { r: 0,   g: 180, b: 140 },
  MODERATE: { r: 220, g: 170, b: 40  },
  ELEVATED: { r: 230, g: 110, b: 30  },
  HIGH:     { r: 210, g: 50,  b: 50  },
  UNKNOWN:  { r: 100, g: 100, b: 120 },
};

const FLAG_TYPE_LABELS = { danger: "HIGH RISK", warn: "WARNING", clean: "CLEAN", info: "INFO" };

function hex(c) {
  return `#${c.r.toString(16).padStart(2,"0")}${c.g.toString(16).padStart(2,"0")}${c.b.toString(16).padStart(2,"0")}`;
}

function generateComplianceReport(walletData, stream) {
  const { address, account, risk, meta, transactions = [] } = walletData;
  const doc = new PDFDocument({ size: "A4", margin: 50, bufferPages: true });
  doc.pipe(stream);

  const W      = doc.page.width;
  const MARGIN = 50;
  const levelColor = LEVEL_COLORS[risk.level] || LEVEL_COLORS.UNKNOWN;

  // ── Header bar ──────────────────────────────────────────────────────────────
  doc.rect(0, 0, W, 80).fill("#0a0f1c");
  doc.fontSize(22).font("Helvetica-Bold").fillColor("#00d4aa").text("SolTrace", MARGIN, 22);
  doc.fontSize(10).font("Helvetica").fillColor("#667788")
     .text("Solana Wallet AML Compliance Report", MARGIN, 48);
  doc.fontSize(9).fillColor("#445566").text(
    `Generated: ${new Date(meta?.fetchedAt || Date.now()).toUTCString()}`,
    W - MARGIN - 200, 48, { width: 200, align: "right" }
  );

  // ── Wallet address ───────────────────────────────────────────────────────────
  doc.moveDown(3);
  doc.fontSize(9).font("Helvetica-Bold").fillColor("#667788").text("WALLET ADDRESS", MARGIN);
  doc.fontSize(10).font("Helvetica").fillColor("#112233")
     .text(address, MARGIN, doc.y + 2, { width: W - MARGIN * 2 });

  // ── Risk score banner ────────────────────────────────────────────────────────
  const bannerY = doc.y + 12;
  doc.roundedRect(MARGIN, bannerY, W - MARGIN * 2, 80, 8)
     .fillColor(hex(levelColor)).fill();

  doc.fontSize(48).font("Helvetica-Bold").fillColor("white")
     .text(String(risk.score), MARGIN + 20, bannerY + 14, { width: 80, align: "center" });
  doc.fontSize(10).font("Helvetica").fillColor("rgba(255,255,255,0.7)")
     .text("/ 100", MARGIN + 20, bannerY + 60, { width: 80, align: "center" });

  doc.fontSize(22).font("Helvetica-Bold").fillColor("white")
     .text(risk.level, MARGIN + 120, bannerY + 26);
  doc.fontSize(10).font("Helvetica").fillColor("rgba(255,255,255,0.8)")
     .text(levelDesc(risk.level), MARGIN + 120, bannerY + 54, { width: W - MARGIN * 2 - 140 });

  doc.y = bannerY + 96;

  // ── Account summary ──────────────────────────────────────────────────────────
  sectionTitle(doc, "ACCOUNT SUMMARY", MARGIN);
  table(doc, [
    ["SOL Balance",           `${account?.solBalance || "0"} SOL`],
    ["Account Type",           account?.type || "unknown"],
    ["Transactions Analysed",  String(meta?.txCount || 0)],
    ["Helius Enhanced",        meta?.heliusEnabled ? "Yes" : "No"],
  ], MARGIN, W);

  // ── Risk flags ───────────────────────────────────────────────────────────────
  sectionTitle(doc, "RISK FLAGS", MARGIN);
  for (const flag of risk.flags) {
    const color =
      flag.type === "danger" ? "#f04040" :
      flag.type === "warn"   ? "#f0c040" :
      flag.type === "clean"  ? "#00d4aa" : "#667788";
    doc.fontSize(9).font("Helvetica-Bold").fillColor(color)
       .text(`[${FLAG_TYPE_LABELS[flag.type] || flag.type.toUpperCase()}]`, MARGIN, doc.y, { continued: true, width: 100 });
    doc.font("Helvetica").fillColor("#223344")
       .text(`  ${flag.label}`, { width: W - MARGIN * 2 - 10 });
    doc.moveDown(0.3);
  }

  // ── Detailed findings ────────────────────────────────────────────────────────
  sectionTitle(doc, "DETAILED FINDINGS", MARGIN);
  for (const detail of risk.details) {
    doc.fontSize(9).font("Helvetica").fillColor("#334455")
       .text(`• ${detail}`, MARGIN, doc.y, { width: W - MARGIN * 2 });
    doc.moveDown(0.4);
  }

  // ── Recent transactions ──────────────────────────────────────────────────────
  if (transactions.length > 0) {
    sectionTitle(doc, "RECENT TRANSACTIONS", MARGIN);
    tableWithHeader(doc,
      ["Signature", "Amount", "Status"],
      transactions.slice(0, 8).map(t => [
        t.signature ? `${t.signature.slice(0, 14)}…` : "—",
        t.lamport   ? `${(t.lamport / 1e9).toFixed(4)} SOL` : "—",
        t.status || "—",
      ]),
      MARGIN, W
    );
  }

  // ── Footer with watermark (IP protection) ────────────────────────────────────
  const pages = doc.bufferedPageRange();
  for (let i = 0; i < pages.count; i++) {
    doc.switchToPage(pages.start + i);
    doc.rect(0, doc.page.height - 48, W, 48).fill("#0a0f1c");

    // Watermark line
    doc.fontSize(7).font("Helvetica-Bold").fillColor("#00d4aa")
       .text(
         "SolTrace · Proprietary AML Intelligence Engine · © 2024 SolTrace. All rights reserved.",
         MARGIN, doc.page.height - 40, { width: W - MARGIN * 2, align: "center" }
       );
    // Disclaimer
    doc.fontSize(7).font("Helvetica").fillColor("#445566")
       .text(
         "This report is generated for compliance and investigative purposes only. SolTrace provides probabilistic risk signals, not legal determinations. Unauthorized reproduction of this report is prohibited.",
         MARGIN, doc.page.height - 28, { width: W - MARGIN * 2, align: "center" }
       );
  }

  doc.end();
}

function levelDesc(level) {
  return {
    LOW:      "No significant AML risk indicators detected.",
    MODERATE: "Some risk signals present — review recommended.",
    ELEVATED: "Multiple risk factors identified — enhanced due diligence required.",
    HIGH:     "Severe risk indicators — escalate to compliance team immediately.",
    UNKNOWN:  "Insufficient transaction history to assess.",
  }[level] || "";
}

function sectionTitle(doc, title, margin) {
  doc.moveDown(0.8);
  doc.fontSize(8).font("Helvetica-Bold").fillColor("#00d4aa").text(title, margin);
  doc.moveTo(margin, doc.y + 2)
     .lineTo(doc.page.width - margin, doc.y + 2)
     .strokeColor("#1e2a3a").lineWidth(0.5).stroke();
  doc.moveDown(0.5);
}

function table(doc, rows, margin, pageWidth) {
  for (const [label, value] of rows) {
    const y = doc.y;
    doc.fontSize(8.5).font("Helvetica-Bold").fillColor("#556677")
       .text(label, margin, y, { width: 160 });
    doc.fontSize(8.5).font("Helvetica").fillColor("#112233")
       .text(value, margin + 170, y, { width: pageWidth - margin * 2 - 170 });
    doc.moveDown(0.45);
  }
}

function tableWithHeader(doc, headers, rows, margin, pageWidth) {
  const colW   = (pageWidth - margin * 2) / headers.length;
  const startY = doc.y;

  doc.rect(margin, startY, pageWidth - margin * 2, 18).fill("#111b2e");
  headers.forEach((h, i) => {
    doc.fontSize(7.5).font("Helvetica-Bold").fillColor("#00d4aa")
       .text(h, margin + i * colW + 4, startY + 5, { width: colW - 8 });
  });
  doc.y = startY + 22;

  rows.forEach((row, ri) => {
    const rowY = doc.y;
    if (ri % 2 === 0) doc.rect(margin, rowY, pageWidth - margin * 2, 16).fill("#f8fafc");
    row.forEach((cell, i) => {
      doc.fontSize(7.5).font("Helvetica").fillColor("#223344")
         .text(cell, margin + i * colW + 4, rowY + 4, { width: colW - 8 });
    });
    doc.y = rowY + 18;
  });
  doc.moveDown(0.5);
}

module.exports = { generateComplianceReport };
